Suppose we need to find the third column of a matrix. There is an easy and efficient way to do it and a harder, less efficient way to do it. The obvious way to do it - with nested four loops and checks against the third column - is inefficient. There is a much better way to do it but first here's the inefficent way.

In [ ]:
import numpy as np
import random as r

In [4]:
matrix = np.array([[r.randint(0, 70) for b in range(10)] for c in range(1000)])

[[ 7 26 53 ... 15  2 14]
 [18 62 19 ... 68 48 45]
 [ 0 43 64 ... 68  3 10]
 ...
 [37 45 18 ... 17 38 31]
 [57 61 28 ...  1 19 60]
 [ 7 69  3 ... 54 26 44]]


In [5]:
column = []
for row in matrix:
    for i in range(len(row)):
        if i == 2:
            column.append(row[i])
print(column[:10])

[np.int64(53), np.int64(19), np.int64(64), np.int64(12), np.int64(8), np.int64(39), np.int64(8), np.int64(68), np.int64(64), np.int64(0)]


That did work but it's way more code than it needs to be! Just do this instead:

In [ ]:
column = matr